class CreateIcons
  def call
    
    Icon.create!( :icon_css => "fa-deviantart", :name =>"Deviantart", :top_icons => false)
    Icon.create!( :icon_css => "fa-digg", :name =>"Digg", :top_icons => false)
    Icon.create!( :icon_css => "fa-dribbble", :name =>"Dribbble", :top_icons => false)
    Icon.create!( :icon_css => "fa-etsy", :name =>"Etsy", :top_icons => false)
    Icon.create!( :icon_css => "fa-facebook", :name =>"Facebook", :top_icons => true)
    Icon.create!( :icon_css => "fa-flickr", :name =>"Flickr", :top_icons => false)
    Icon.create!( :icon_css => "fa-foursquare", :name =>"Foursquare", :top_icons => false)
    Icon.create!( :icon_css => "fa-github", :name =>"Github", :top_icons => false)
    Icon.create!( :icon_css => "fa-google-plus", :name =>"Google-Plus", :top_icons => true)
    Icon.create!( :icon_css => "fa-houzz", :name =>"Houzz", :top_icons => false)
    Icon.create!( :icon_css => "fa-instagram", :name =>"Instagram", :top_icons => true)
    Icon.create!( :icon_css => "fa-linkedin", :name =>"Linkedin", :top_icons => true)
    Icon.create!( :icon_css => "fa-pinterest", :name =>"Pinterest", :top_icons => true)
    Icon.create!( :icon_css => "fa-quora", :name =>"Quora", :top_icons => false)
    Icon.create!( :icon_css => "fa-reddit", :name =>"Reddit", :top_icons => true)
    Icon.create!( :icon_css => "fa-skype", :name =>"Skype", :top_icons => false)
    Icon.create!( :icon_css => "fa-slack", :name =>"Slack", :top_icons => false)
    Icon.create!( :icon_css => "fa-slideshare", :name =>"Slideshare", :top_icons => false)
    Icon.create!( :icon_css => "fa-snapchat", :name =>"Snapchat", :top_icons => false)
    Icon.create!( :icon_css => "fa-snapchat-ghost", :name =>"Snapchat-Ghost", :top_icons => false)
    Icon.create!( :icon_css => "fa-soundcloud", :name =>"Soundcloud", :top_icons => false)
    Icon.create!( :icon_css => "fa-spotify", :name =>"Spotify", :top_icons => false)
    Icon.create!( :icon_css => "fa-stumbleupon", :name =>"Stumbleupon", :top_icons => false)
    Icon.create!( :icon_css => "fa-trello", :name =>"Trello", :top_icons => false)
    Icon.create!( :icon_css => "fa-tumblr", :name =>"Tumblr", :top_icons => false)
    Icon.create!( :icon_css => "fa-twitter", :name =>"Twitter", :top_icons => true)
    Icon.create!( :icon_css => "fa-vimeo", :name =>"Vimeo", :top_icons => true)
    Icon.create!( :icon_css => "fa-vine", :name =>"Vine", :top_icons => false)
    Icon.create!( :icon_css => "fa-whatsapp", :name =>"Whatsapp", :top_icons => false)
    Icon.create!( :icon_css => "fa-wikipedia-w", :name =>"Wikipedia-W", :top_icons => false)
    Icon.create!( :icon_css => "fa-wordpress", :name =>"Wordpress", :top_icons => false)
    Icon.create!( :icon_css => "fa-yelp", :name =>"Yelp", :top_icons => true)
    Icon.create!( :icon_css => "fa-youtube", :name =>"Youtube", :top_icons => true)
 
  end
end
