# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
GMAIL_USERNAME: ruby.rails.chris
GMAIL_PASSWORD: 4tobytoby
ADMIN_NAME: Chris Mailloux
ADMIN_EMAIL: chrismayu@gmail.com
ADMIN_PASSWORD: tobytoby
SECRET_KEY_BASE: 739937333cb6c535e798347893434ius23r23349g39gh32423423423423423894g83jiihfsdhfsdhfisdhf08weh08efh26b724634346346346346338b4035982ce1905d8492e49d246c570a8f247954049d223d209c2332b8819f55f17853295565988fdca80cd8c71cfd7049bff8c
DOMAIN_NAME: letschat.cc 
ROLLBAR_ACCESS_TOKEN: 1a0f03a032724d56b7f8905e1ae51b14
return_email_address: info@letschat.cc 
SITE_EMAIL: techsupport@letschat.cc 
ADAM_EMAIL: info@cmiforms.com 
ROLES: '[admin, user, VIP]'
URL: 'http://www.letschat.cc/'
 
MANDRILL_USERNAME: 'hope.inter.web@gmail.com'
MANDRILL_API_KEY: jfjm4v7SpO64ChKatwfd3w

TZ: America/Detroit 

AWS_S3_BUCKET: letschat-cc
AWS_SECRET_ACCESS_KEY: EnBRtnNnmRyBBsoIxrCg1YbOvCKI31xSS4b3f36t
AWS_ACCESS_KEY_ID: AKIAJ2JCK7UO3N6CP3CQ
